config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :words, only: [:new, :create, :destroy]

  root 'words#index'

  if Rails.env.development?
    get '/oops', to: 'words#oops'
    get '/dupe', to: 'words#dupe'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  validates :value, presence: true
  validates :value, uniqueness: { case_sensitive: false }

  self.per_page = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  if Rails.env.production?
    force_ssl
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    auth = request.env["omniauth.auth"]

    if !Rails.configuration.x.allowed_users.include? auth.info.email
      flash.alert = "You are not authorized to log into this app"
      redirect_to new_user_session_url
    else
      @user = User.from_omniauth(auth)


      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!
  before_action :has_id, only: :destroy
  before_action :validate_word, only: :create

  def index
    if params[:search]
      @words = Word.page(params[:page]).where('value LIKE ?', "%#{params[:search]}%").order('value asc')
    else
      @words = Word.page(params[:page]).order('value asc')
    end
  end

  def create
    if @word.save
      redirect_to :root
    else
      oops
    end
  end

  def new
    render "new"
  end

  def destroy
    if params[:id].nil?
      oops
    else
      word = Word.find_by id: params[:id]
      if word.destroy
        redirect_to :root
      else
        oops
      end
    end
  end

  def oops
    render "oops"
  end

  def dupe
    render "dupe"
  end

  private

  def

  def has_id
    if params[:id].nil?
      oops
    end
  end

  def haz_value
    if params[:word][:value].nil?
      oops
    end
  end

  def validate_word
    @word = Word.new value: params[:word][:value]

    if @word.invalid?
      dupe
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LilyWordCounter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style media="screen">
    body { padding-top: 70px; }
  </style>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"></head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">
        LilyBug Word Tracker
      </a>
      <% if user_signed_in? %>
        <%= button_to "Logout", destroy_user_session_url, :class => "btn btn-primary navbar-btn navbar-right", :method => :delete %>
      <% else %>
        <%= render "devise/shared/links" %>
      <% end %>
    </div>
  </nav>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/words/dupe.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
    ooops!
  </div>
  <div class="panel-body">
    <p>
      LilyBug knows that word already, silly
    </p>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <%= button_to "Okay",root_url, method: 'get', class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/words/index.html.erb
<div class="row">
  <div class="col-xs-12 col-xs-offset-2 col-md-offset-1">
    <h3>
    </h3>
</div>
</div>

<% if user_signed_in? %>
  <div class="row">
    <div class="col-xs-offset-1 col-xs-10 col-md-6 col-md-offset-1">
      <%= button_to "Add Word", new_word_path, :class => "btn btn-primary btn-block", :method => :get %>
    </div>
  </div>
  <br />
<% end %>

<div class="row">
  <div class="col-xs-offset-1 col-xs-10 col-md-6 col-md-offset-1">
    <%= form_tag '/', :method => 'get' do %>
    <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control" %>
        <span class="input-group-btn">
          <button class="btn btn-primary" type="submit">Find Word</button>
        </span>
      <% end %>
    </div>
  </div>
</div>

<br />

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-6">
    <div class="table-responsive">
      <table class="table table-bordered">
        <% @words.each do |word| %>
          <tr>
            <td class="col-lg-10 col-md-10 col-sm-8 col-xs-8">
              <%= word.value %>
            </td>
            <td class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
              <% if user_signed_in? %>
                <%= button_to word, method: "delete", class: "btn btn-primary btn-xs", data: { confirm: "LilyBug forgot this word?" } do %>
                  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-xs-12">
      <%= will_paginate @words, renderer: BootstrapPagination::Rails %>
    </div>
    <div class="col-xs-12">
      <%= page_entries_info %>
    </div>
  </div>
</div>

app/views/words/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Add Word - Yay!</div>
  <div class="panel-body">
    <div class="row">
      <%= bootstrap_form_for :word, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8", url: {action: "create"}, class: "" do |f| %>
      <%= f.text_field :value %><br />
      <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <%= f.submit "Add Word", class: "btn btn-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/words/oops.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
    ooops!
  </div>
  <div class="panel-body">
    <p>
      Something broke, tell Daddy to fix it
    </p>
    </div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <%= button_to "Okay",root_url, method: 'get', class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
</div>